/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "Workers": "工人",
    "Working at Factory": "在工厂工作",
    "Working at Lab": "在实验室工作",
    "Working at Launch Pad": "在发射台工作",
    "Working at Mine": "在煤矿工作",
    "Working at Q. Transport": "在量子传输工作",
    "You win! Congratulations and thanks for playing!": "你赢了！ 恭喜并感谢您的参与！",
    "auto": "自动",
    "Build (F)actory": "建造工厂（F）",
    "Build (H)ouse": "建造房子（H）",
    "Build (L)ab": "建造实验室（L）",
    "Build (Q)uantum Transport": "建造量子传输（Q）",
    "Build (R)adio Telescope": "建造无线电望远镜（R）",
    "Build L(a)unch Pad": "建造发射台（A）",
    "Build S(e)rver": "建造服务器（E）",
    "Build Solar (P)anel": "建造太阳能板（P）",
    "Build Options": "建造选项",
    "Building Info": "建筑信息",
    "Can use up to 5 population.": "最多可使用 5 人。",
    "Click here for the sun view": "单击此处查看太阳视图",
    "Click this window to close it.": "单击此窗口将其关闭。",
    "Costs 1 solar panel. Provides 1 electricity.": "成本 1 个太阳能电池板。 提供1电。",
    "Costs 100 ore and 5 panels. Increases max pop by 10. Pop increases by .1%": "需要 100 矿石和 5 太阳能板。 最大流行度增加 10。流行度增加 0.1%",
    "Costs 10k electronics. Can send resources to any planet in range using power, but uses more power for more distance.": "花费 10K 电力设备。 可以使用能量将资源发送到范围内的任何行星，但使用更多能量来获得更远的距离。",
    "Costs 10m ore, 2m electronics, and 200 power. Creates and launches solar sails from solar panels & ore.": "花费 10M 矿石、2M 电力设备和 200 电力。 用太阳能电池板和矿石制造和发射太阳帆。",
    "Costs 1k electronics and uses 25 electricity. Creates virtual population with all excess population growth. Holds 1k virtual population.": "花费 1k 个电子设备并使用 25 电。 创建具有所有超额人口增长的虚拟人口。 拥有 1k 虚拟人口。",
    "Costs 20 electronics and 5 electricity. Provides 1 science per second..": "花费 20 个电力设备和 5 个电力。 每秒提供 1 科学..",
    "Costs 20k ore and 1000 solar panels. Can receive virtual population, or up to 50 power from the Dyson Sphere from the closest planet onwards.": "成本 20k 矿石和 1000 太阳能电池板。 可以从最近的行星开始从戴森球接收虚拟人口或最多 50 点能量。",
    "Pause (Space": "暂停 (空格",
    "Planet Info": "星球信息",
    "Planet View": "星球查看",
    "Population": "人口",
    "Research": "研究",
    "Solar Panels": "太阳能板",
    "Solar Sails": "太阳帆",
    "That's all... for now": "就这些……暂时",
    "The goal is to build a Dyson Sphere around the sun, piece by piece. There's 31415 solar sails to place around the sun, good luck!": "目标是一块一块地围绕太阳建造一个戴森球。 有 31415 个太阳帆可以围绕太阳放置，祝你好运！",
    "Then, build a solar panel - you start with 1 - and a factory with the ore from the mines, and use the factory to get another solar panel, for another factory, etc.": "然后，建造一个太阳能电池板 - 你从 1 开始 - 和一个带有矿山矿石的工厂，并使用该工厂获得另一个太阳能电池板，用于另一个工厂，等等。",
    "This game is made for the incremental jam by Stop_Sign!": "这个游戏是由Stop_Sign为incremental jam制作的！",
    "To start, click on ore and build mines - they're free to build, so cover each of the mines right away!": "首先，点击矿石并建造矿井 - 它们可以自由建造，所以立即覆盖每个矿井！",
    "Total seconds played": "总游戏秒数",
    "U)pgrade": "升级（U）",
    "Unlock House": "解锁房子",
    "Use the arrow keys to move around the grid": "使用箭头键在网格中移动",
    "Uses 1 electricity.": "使用 1 电力。",
    "Get some science with a lab, and keep unlocking new pieces until you can harness the power of the sun!": "在实验室获得一些科学知识，并不断解锁新作品，直到您可以利用太阳的力量！",
    "Get population and workers! Each worker assigned to an industry increases output by 5%!": "获取人口和工人！ 每个分配到一个行业的工人增加 5% 的产量！",
    "Free to build. Gain ore per second.": "免费搭建。 每秒获得矿石。",
    "Science": "科学",
    "S)ell": "出售（S）",
    "Press the key surrounded by () to build that building or do that action": "按 () 包围的键来建造该建筑物或执行该操作",
    "Ore": "矿石",
    "Shift + [num] moves to other planets, when you unlock them": "Shift + [数字] 移动到其他行星，当你解锁它们时",
    "or solar panels from electronics.": "或电力设备的太阳能电池板。",
    "of current population every second.": "当前人口每秒。",
    "Minimum 2 population.": "最少 2 人。",
    "M)ine": "矿井（M）",
    "Launching": "发射",
    "Help": "帮助",
    "Escape closes error messages": "转义关闭错误消息",
    "Electronics": "电力设备",
    "Electricity": "电力",
    "Dyson Sphere progress": "戴森球进度",
    "Don't be afraid to sell, there's a 100% return policy always, but be careful of selling electricity buildings and crashing the power grid.": "不要害怕出售，总是有 100% 的退货政策，但要小心出售电力建筑和破坏电网。",
    "Distance from sun": "与太阳的距离",
    "Costs 50 ore. Creates electronics from ore,": "花费 50 矿石。 用矿石制造电力设备，",
    "electricity.": "电力。",
    "Gain": "获取",
    "Harness the light of the sun for electricity! Buildings will not work without electricity.": "利用太阳的光来发电！ 没有电，建筑物将无法运转。",
    "Mine": "矿井",
    "ore per second.": "矿石每秒。",
    "Solar Panel": "太阳能板",
    "Create": "创建",
    "electronics using 10x the ore per second, or": "电力设备每秒使用 10 倍的矿石，或",
    "ERROR: Adding a Factory right now would crash the power grid!": "错误：现在添加工厂会导致电网崩溃！",
    "Factory": "工厂",
    "solar panels using 2x the electronics per second": "太阳能电池板每秒使用 2 倍的电力设备",
    "ERROR: Adding a Lab right now would crash the power grid!": "错误：现在添加实验室会导致电网崩溃！",
    "SP": "板",
    "E": "设",
    "science per second.": "科学每秒。",
    "An upgrade to the mine. Double production, but more expensive to build. Comes with solar panels instead of an electricity requirement.": "矿井的升级。 双倍产量，但建造成本更高。 配备太阳能电池板，而不是电力需求。",
    "ERROR: You need 10 more free workers to sell this house!": "错误：你还需要 10 个空闲工人才能卖掉这栋房子！",
    "Holds": "持有",
    "House": "房子",
    "Let the light shine upon the non-believers.": "让光照在非信徒身上。",
    "people in it. Population increases by .1% per second. Assign workers to other buildings to improve their efficiency by 5% per worker.": "里面的人。 人口每秒增加 0.1%。 将工人分配到其他建筑物，以将每个工人的效率提高 5%。",
    "Lab": "实验室",
    "Even more efficiency! You get the drill": "效率更高！ 你得到钻头",
    "More ore already? Well alright, but it'll cost ya.": "已经有更多矿石了吗？ 好吧，但它会花费你。",
    "New houses taking too much space? Upload your extra population instead!": "新房太占地方？ 改为上传您的额外人口！",
    "Unlock Servers": "解锁服务器",
    "Upgrade the factory, doubling efficiency.": "升级工厂，倍增效率。",
    "Upgrade the lab, triple the gain at only double the power! You get the idea.": "升级实验室，以两倍的功率获得三倍的收益！ 你明白了。",
    "Within you is the light of a thousand suns.": "你内在是一千个太阳的光。",
    "Finally, improvements to housing technology: 2 floors": "最后，改善住房技术：2层",
    "It is during our darkest moments that we must focus to see the light.": "在我们最黑暗的时刻，我们必须集中注意力才能看到光明。",
    "Send resources to other planets, kick-starting them into eventually sending resources back! Electricity cost is dependent on distance.": "将资源发送到其他星球，启动它们最终将资源送回！ 电费取决于距离。",
    "The next in the line.": "在该行的下一个。",
    "Unlock Quantum Transport": "解锁量子传输",
    "V. Pop.": "虚拟人口",
    "Server": "服务器",
    "virtual people in it. Extra population growth becomes virtual people. Virtual people can be workers, but they don't contribute to population growth. Can only hold 1 server per planet.": "虚拟人在里面。 额外的人口增长成为虚拟人。 虚拟人可以是工人，但他们对人口增长没有贡献。 每个星球只能容纳 1 个服务器。",
    "ERROR: Upgrading this Lab right now would crash the power grid!": "错误：现在升级这个实验室会导致电网崩溃！",
    "ERROR: Upgrading this Factory right now would crash the power grid!": "错误：现在升级这个工厂会导致电网崩溃！",
    "Significant improvement to efficiency!": "显著提高效率！",
    "ERROR: Cannot build another server - only 1 server allowed per planet!": "错误：无法建立另一个服务器 - 每个星球只允许 1 个服务器！",
    ". Send 1 ore, .1 electronic, .05 solar panels, .005 solar sails, or .01 virtual population per transfer rate. Virtual population will only transfer if the target planet has a Radio Telescope AND this planet has workers available. Improve the transfer rate with workers!": ". 每个传输速率发送 1 个矿石、0.1 个电子、0.05 个太阳能板、0.005 个太阳帆或 0.01 个虚拟人口。 只有当目标星球有射电望远镜并且这个星球有可用的工人时，虚拟人口才会转移。 提高与工人的转移率！",
    "Costs": "成本",
    "ERROR: Can't start mining until the planet is connected to a Quantum Transport! Send any resource to this planet and you can start mining.": "错误：在行星连接到量子传输之前无法开始采矿！ 将任何资源发送到这个星球，你就可以开始挖矿了。",
    "Gain Factory Mk. 4, which is an improvement over Mk. 3!": "获得工厂Mk. 4，这是对Mk. 3的改进！",
    "Only when we are brave enough to explore the darkness will we discover the infinite power of our light.": "只有勇于探索黑暗，才能发现光明的无限力量。",
    "power to send resources a distance of": "将资源发送到一定距离的电力",
    "Quantum Transport": "量子传输",
    "Receive virtual population from other planets, and later power from your Dyson Sphere": "从其他星球接收虚拟人口，然后从您的戴森球获得能量",
    "Send": "发送",
    "Send resources to other planets. Base transfer rate is": "将资源发送到其他星球。 基本传输速率为",
    "Send to planet": "发送到星球",
    "Unlock Radio Telescope": "解锁射电望远镜",
    "Turns off when you switch planets.": "切换行星时关闭。",
    "Allows for virtual population to be sent to this planet via Quantum Transporters. Alternatively, can receive up to": "允许通过量子传输器将虚拟人口发送到这个星球。 或者，最多可以接收",
    "Radio Telescope": "射电望远镜",
    "Receive": "接收",
    "electricity from the Dyson Sphere.": "来自戴森球的电力。",
    "VP": "虚",
    "Holds 50 people": "可容纳50人",
    "Holds 5000 virtual people": "可容纳5000虚拟人口",
    "More ore for a higher premium.": "更多的矿石以获得更高的溢价。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",

    //树游戏
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "Electricity use: ": "电力使用: ",
    "Electronics (": "电力设备 (",
    "Solar Panels (": "太阳能板 (",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "Some hotkeys": "快捷键",
    "The game saves every 20 seconds.": "游戏每 20 秒保存一次。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)T$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^E>P(\d+)$/, '设>星$1'],
    [/^O>P(\d+)$/, '矿>星$1'],
    [/^SP>P(\d+)$/, '板>星$1'],
    [/^SS>P(\d+)$/, '帆>星$1'],
    [/^VP>P(\d+)$/, '虚>星$1'],
    [/^Electricity \((\d+)$/, '电力 \($1'],
    [/^Population \((\d+)$/, '人口 \($1'],
    [/^Solar Sails \((\d+)$/, '太阳帆 \($1'],
    [/^V. Population \((\d+)$/, '虚拟人口 \($1'],
    [/^Ore \((\d+)$/, '矿石 \($1'],
    [/^Planet (\d+)$/, '星球 $1'],
    [/^Unlock Mine Mk. (\d+)$/, '解锁矿井 Mk. $1'],
    [/^Unlock Server Mk. (\d+)$/, '解锁服务器 Mk. $1'],
    [/^Unlock Lab Mk. (\d+)$/, '解锁实验室 Mk. $1'],
    [/^Unlock Solar Panel Mk. (\d+)$/, '解锁太阳能板 Mk. $1'],
    [/^Unlock Solar Mk. (\d+)$/, '解锁太阳 Mk. $1'],
    [/^Unlock House Mk. (\d+)$/, '解锁房子 Mk. $1'],
    [/^Unlock Factory Mk. (\d+)$/, '解锁工厂 Mk. $1'],
    [/^Upgrade to Mk. (\d+) for$/, '升级到 Mk. $1 成本'],
    [/^Buy for (.+) science$/, '购买成本 $1 科学'],
    [/^ERROR: Unlock Quantum Transport Mk. (.+) costs (.+) research points. You have (.+)$/, '错误：解锁量子传输 Mk. $1 花费 $2 研究点。 你有 $3'],
    [/^ERROR: Unlock Solar Panel Mk. (.+) costs (.+) research points. You have (.+)$/, '错误：解锁太阳能板 Mk. $1 花费 $2 研究点。 你有 $3'],
    [/^ERROR: Unlock Factory Mk. (.+) costs (.+) research points. You have (.+)$/, '错误：解锁工厂 Mk. $1 花费 $2 研究点。 你有 $3'],
    [/^ERROR: Unlock Lab Mk. (.+) costs (.+) research points. You have (.+)$/, '错误：解锁实验室 Mk. $1 花费 $2 研究点。 你有 $3'],
    [/^ERROR: Unlock House Mk. (.+) costs (.+) research points. You have (.+)$/, '错误：解锁房子 Mk. $1 花费 $2 研究点。 你有 $3'],
    [/^ERROR: Unlock Server Mk. (.+) costs (.+) research points. You have (.+)$/, '错误：解锁服务器 Mk. $1 花费 $2 研究点。 你有 $3'],
    [/^ERROR: Unlock Mine Mk. (.+) costs (.+) research points. You have (.+)$/, '错误：解锁矿井 Mk. $1 花费 $2 研究点。 你有 $3'],
    [/^ERROR: Unlock Solar Mk. (.+) costs (.+) research points. You have (.+)$/, '错误：解锁太阳 Mk. $1 花费 $2 研究点。 你有 $3'],
    [/^ERROR: Solar Panel costs 1 panels. You have (.+) panels.$/, '错误：太阳能板需要 1 太阳能板。你有 $1 太阳能板。'],
    [/^ERROR: Unlock Quantum Transport costs 250000 research points. You have (.+)$/, '错误：解锁量子传输需要 250000 研究点。你有 $1'],
    [/^ERROR: Unlock House costs 100 research points. You have (.+)$/, '错误：解锁房子需要 100 研究点。你有 $1'],
    [/^ERROR: Unlock Servers costs 10000 research points. You have (.+)$/, '错误：解锁服务器需要 10000 研究点。你有 $1'],
    [/^ERROR: Unlock Radio Telescope costs 400000 research points. You have (.+)$/, '错误：解锁射电望远镜需要 10000 研究点。你有 $1'],
    [/^ERROR: Factory costs 50 ore. You have (.+) ore.$/, '错误：工厂需要 50 矿石。你有 $1 矿石。'],
    [/^ERROR: Quantum Transport costs 10000 electronics. You have (.+) electronics.$/, '错误：量子传输需要 10000 电力设备。你有 $1 电力设备。'],
    [/^ERROR: Server costs 1000 electronics. You have (.+) electronics.$/, '错误：服务器需要 1000 电力设备。你有 $1 电力设备。'],
    [/^ERROR: Lab costs 20 electronics. You have (.+) electronics.$/, '错误：实验室需要 20 电力设备。你有 $1 电力设备。'],
    [/^ERROR: Radio Telescope costs (.+) ore and (.+) panels. You have (.+) ore and (.+) panels.$/, '错误：射电望远镜需要 $1 个矿石和 $2 个太阳能板。 你有 $3 矿石和 $4 太阳能板。'],
    [/^ERROR: Mine costs (.+) electronics and (.+) panels. You have (.+) electronics and (.+) panels.$/, '错误：矿井需要 $1 电力设备和 $2 个太阳能板。 你有 $3 电力设备和 $4 太阳能板。'],
    [/^ERROR: House costs (.+) ore and (.+) panels. You have (.+) ore and (.+) panels.$/, '错误：房子需要 $1 个矿石和 $2 个太阳能板。 你有 $3 矿石和 $4 太阳能板。'],
    [/^ERROR: Factory costs (.+) ore and (.+) electronics. You have (.+) ore and (.+) electronics.$/, '错误：工厂需要 $1 个矿石和 $2 个电子设备。 你有 $3 矿石和 $4 电子设备。'],
    [/^ERROR: Solar Panel costs (.+) panels. You have (.+) panels.$/, '错误：太阳能板需要 $1 块太阳能板。 您有 $2 个太阳能板。'],
    [/^ERROR: Unpausing this Quantum Transport will crash the power grid! Need (.+) to unpause.$/, '错误：取消暂停此量子传输将使电网崩溃！ 需要 $1 才能取消暂停。'],
    [/^ERROR: You need (.+) more free workers to sell this house!$/, '错误：你还需要 $1 个自由工人才能卖掉这栋房子！'],
    [/^Effect will increase from ([\d\.]+) to ([\d\.]+)$/, '效果将从 $1 增加到 $2'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);